services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    command: npm run dev

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    command: npm run dev