name: Backend Docker Build and Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build-and-run:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build Docker image
      run: docker build -t backend .
      working-directory: ./backend
    - name: Run Docker container
      run: docker run -d -p 3000:3000 backend
